### ISSUE TITLE
The number of open connections is too high

### ISSUE THREAD

**Issue by alejandromiller21** [arangodb/kube-arangodb#1381]
In my Kube-arangodb with 3 nodes, I have _system, and 2 other databases, but I see around 310 opened connections all the time, and I can't find a solution. Around 100 connections are open on each node. How normal is this?

![image](https://github.com/arangodb/kube-arangodb/assets/89926156/fa3fe4f8-b1b6-4cf1-9450-906b005ff897)

**Comment by ajanikow** [comment]
Hello!

Can you share ArangoDB and Operator versions?

Best,
Adam.

**Comment by alejandromiller21** [comment]
Hi! 
My helm chart uses kube-arangodb-1.2.31 with operator: arangodb/kube-arangodb:1.2.31, and I have tested with arangodb: arango:3.11 as well.

Thanks for your help!

**Comment by ajanikow** [comment]
Hello!

Right now you have 6 nodes on your cluster counted for connections.

Do you have any client applications?

300 connections do not look bad due to keep-alive settings on HTTP (I suppose you use HTTP instead of HTTP2).

Each member (Coordinator & DBServer) uses the pool for internal communication. This means it will keep open connections in communication between DBServers (replication), between Coordinators (for internal communication and request redirections), and between Coordinators and DBServers (for query executions).

Number 300 can be expected if you have a replication factor set to 3, do not use OneShard databases (just standard ones), and use applications that pool data from the cluster (via browser or service).

Best Regards,
Adam.

**Comment by alejandromiller21** [comment]
Thanks for answering me. How can I use HTTP2 instead of HTTP? 
You are right, I have replicas in 3 using databases separated.

Thanks again!

**Comment by ajanikow** [comment]
Hello!

HTTP/HTTP2 is the driver setting, and cannot be changed on the Database side.

For Go: use http2.Transport instead of http.Transport

Best Regards,
Adam.
