### ISSUE TITLE
Limit scaling from web-UI

### ISSUE THREAD

**Issue by ewoutp** [arangodb/kube-arangodb#320]
I would like to restrict the number of servers to which you can scale through the web-UI.

For every server group I expect to set a limit (upper & lower) for the number of servers in that group.
If the user (through the web-UI) tries to go outside those limits, their request is ignored.

**Comment by neunhoef** [comment]
Would it be OK if these limits are configured via the `/_api/cluster/numberOfServers` API? Probably not, because then the user could access that API and change the limits. Or one could only allow the superuser to change this. So it should probably be an option for the coordinators? Then it could not be changed at runtime.

**Comment by ewoutp** [comment]
No, I need the limits to be specified in the Kube-ArangoDB Deployment specification.
