### ISSUE TITLE
Arangodb fails to restart after shutting down and restarting K8S cluster

### ISSUE THREAD

**Issue by AnsonT** [arangodb/kube-arangodb#669]
Using ArangoLocalStorage, restarting a cluster, the coordinating pods are stuck waiting for db nodes, so the cluster is not functional.
prmr pods are stuck in terminating, crdn pods are restarting and failing readiness probe.

arangodb 3.7.3
cluster of 3 agents/dbservers/coordinators

**Comment by ajanikow** [comment]
Hello!

Can you share you Operator version?

Did you kill all pods at the same time?

Best Regards,
Adam.

**Comment by ajanikow** [comment]
Hello!

In case like this we have option to disable dbserver removal checks (your cluster is in state when it wont be able to recover by default).

https://github.com/arangodb/kube-arangodb/blob/master/pkg/apis/deployment/v1/recovery_spec.go#L28 - if you will set `spec.recovery.autoRecover` flag to true operator will be able to restart pods. 

Otherwise - you can edit pod end remove finalizers, so it will be restarted.

Best Regards, 
Adam.

**Comment by AnsonT** [comment]
OK! spec.recovery.autoRecover: true did the trick. Thank you!

**Comment by hikkyu** [comment]
Got the same issue with:
- ArangoDB@3.6.3
- kube-arango@1.1.5
- GKE 1.18.12-gke.1210

But autoRecover did not do the trick, delete finalizer does
