### ISSUE TITLE
Wrong definition in the crd file for 1.1.6

### ISSUE THREAD

**Issue by arthursub** [arangodb/kube-arangodb#693]
Hello, i have encountered a problem when i try to install the arango-crd using "kubectl apply" command.
 There is the problem : 

==> " The CustomResourceDefinition "arangomembmers.database.arangodb.com" is invalid: metadata.name: Invalid value: "arangomembmers.database.arangodb.com": must be spec.names.plural+"."+spec.group"

I tried to modify in the arango-crd file the template for member and instead of putting 
"name: arangomembmers.database.arangodb.com", i have put "name: arangomembers.database.arangodb.com"

And the error was resolved

**Comment by ajanikow** [comment]
Hello!

Thank You for update! 1.1.6 is still not published and wont be, we recommend to use 1.1.5 for now due to that in 1.1.6 there is no change. Fix will be part of 1.1.7. Somehow helm did not fail during CRDs installation as a part of Kube-ArangoDB chart (CRDs directory).

I will link PR with fix for it in this issue. 

Best Regards, 
Adam Janikowski.

**Comment by ajanikow** [comment]
Hello! Fixed in 1.1.7
